server:
  address: localhost
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

file_path: /Users/zenon/Library/Mobile Documents/com~apple~CloudDocs/Desktop/Project/Spring-Service-Project/market/src/main/resources/static/csv/
market_area: market_area.csv
market_benefit: market_benefit.csv
market_sgg_change: market_sgg_change.csv
market_umd_change: market_umd_change.csv
market_store: market_store.csv